config/routes.rb
SampleApp::Application.routes.draw do
  get "static_pages/home"
	get "static_pages/about"
	resources :users
	match '/signup', to: 'users#new'
	

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
	has_secure_password

	before_save { |user| user.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def index
		@users = User.all
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:success] = "Welcome!"
			redirect_to @user
		else
			render 'new'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "RoR tutorial sample app"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)	
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, value| %>
		<div><%= value %></div>
	<% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	The form contains <%= pluralize(@user.errors.count, "error") %>:
	<ul>
	<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us!') %v
<h1>About us</h1>
<p>
All I want to say is: "they don't really care about us!" :P
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Sample App</h1>
<p>
	This is the home page for the tutorial :)<br>
</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<p>
		<%= gravatar_for user%><br>
		Nome: <%= user.name %><br>
		Email: <%= user.email %><br>
		<%= link_to "Ver perfil", user_path(user.id) %>
	</p>
<% end %>
<p><%= link_to "Sign up now", signup_path %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :email %><br>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :password %><br>
	<%= f.password_field :password %>
</p>
<p>
	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %>
</p>
<p>
	<%= f.submit "Go!" %>
</p>
<% end %>
<%= link_to "Home", users_path %>

app/views/users/show.html.erb
<p>
<%= gravatar_for @user %>
<%= @user.name %>, <%= @user.email %>
</p>
<%= link_to "Home", users_path %>